// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260609113312_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.AnhThuCung", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnh"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaThuCung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTaiLen")
                        .HasColumnType("datetime2");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaThuCung");

                    b.ToTable("AnhThuCung");
                });

            modelBuilder.Entity("WebApplication1.Models.BaiViet", b =>
                {
                    b.Property<int>("MaBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiViet"));

                    b.Property<string>("DuongDanAnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LaCauChuyenThanhCong")
                        .HasColumnType("bit");

                    b.Property<int>("MaTacGia")
                        .HasColumnType("int");

                    b.Property<int?>("MaThuCung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaBaiViet");

                    b.HasIndex("MaTacGia");

                    b.HasIndex("MaThuCung");

                    b.ToTable("BaiViet");
                });

            modelBuilder.Entity("WebApplication1.Models.BaoCaoCuuHo", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTaChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDoKhanCap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNguoiBaoCao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaBaoCao");

                    b.ToTable("BaoCaoCuuHo");
                });

            modelBuilder.Entity("WebApplication1.Models.ChiPhiCuuHo", b =>
                {
                    b.Property<int>("MaChiPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiPhi"));

                    b.Property<string>("LoaiChiPhi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaThuCung")
                        .HasColumnType("int");

                    b.Property<string>("MucDichChiTiet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayChiTieu")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiXacNhan")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiPhi");

                    b.HasIndex("MaThuCung");

                    b.HasIndex("NguoiXacNhan");

                    b.ToTable("ChiPhiCuuHo");
                });

            modelBuilder.Entity("WebApplication1.Models.ChienDichQuyenGop", b =>
                {
                    b.Property<int>("MaChienDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChienDich"));

                    b.Property<string>("AnhChienDich")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienDaQuyenGop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienMucTieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenChienDich")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChienDich");

                    b.ToTable("ChienDichQuyenGop");
                });

            modelBuilder.Entity("WebApplication1.Models.CongViecTaiTram", b =>
                {
                    b.Property<int>("MaCongViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCongViec"));

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongTNVYeuCau")
                        .HasColumnType("int");

                    b.Property<string>("TenCongViec")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("ThoiGianBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ThoiGianKetThuc")
                        .HasColumnType("time");

                    b.HasKey("MaCongViec");

                    b.ToTable("CongViecTaiTram");
                });

            modelBuilder.Entity("WebApplication1.Models.DiemDanhCongViec", b =>
                {
                    b.Property<int>("MaChiTietPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietPhanCong"));

                    b.Property<bool>("CoMat")
                        .HasColumnType("bit");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<int>("MaTinhNguyenVien")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietPhanCong");

                    b.HasIndex("MaTinhNguyenVien");

                    b.HasIndex("MaCongViec", "MaTinhNguyenVien")
                        .IsUnique();

                    b.ToTable("DiemDanhCongViec");
                });

            modelBuilder.Entity("WebApplication1.Models.DonDangKyTinhNguyen", b =>
                {
                    b.Property<int>("MaDonDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonDangKy"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KyNang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NamSinh")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonDangKy");

                    b.ToTable("DonDangKyTinhNguyen");
                });

            modelBuilder.Entity("WebApplication1.Models.DonNhanNuoi", b =>
                {
                    b.Property<int>("MaDonNhanNuoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonNhanNuoi"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaThuCung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHenPhongVan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonNhanNuoi");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaThuCung");

                    b.ToTable("DonNhanNuoi");
                });

            modelBuilder.Entity("WebApplication1.Models.KhaoSatDieuKienSong", b =>
                {
                    b.Property<int>("MaKhaoSat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhaoSat"));

                    b.Property<bool>("CoHangRaoCao")
                        .HasColumnType("bit");

                    b.Property<bool>("CoLuoiBanCong")
                        .HasColumnType("bit");

                    b.Property<bool>("CoSanVuon")
                        .HasColumnType("bit");

                    b.Property<string>("KinhNghiemNuoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiNhaO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaDonNhanNuoi")
                        .HasColumnType("int");

                    b.Property<string>("SuDongYCoGiaDinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThoiGianRanhMoiNgay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhaoSat");

                    b.HasIndex("MaDonNhanNuoi")
                        .IsUnique();

                    b.ToTable("KhaoSatDieuKienSong");
                });

            modelBuilder.Entity("WebApplication1.Models.LichSuSucKhoe", b =>
                {
                    b.Property<int>("MaLichSuSK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSuSK"));

                    b.Property<string>("BacSiThuY")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChuanDoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChuBenhAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaThuCung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichSuSK");

                    b.HasIndex("MaThuCung");

                    b.ToTable("LichSuSucKhoe");
                });

            modelBuilder.Entity("WebApplication1.Models.LichSuTrangThai", b =>
                {
                    b.Property<int>("MaLichSuTT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSuTT"));

                    b.Property<string>("GhiChuThayDoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaThuCung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiThucHien")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiCuuHoSau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiCuuHoTruoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiNhanNuoiSau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiNhanNuoiTruoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichSuTT");

                    b.HasIndex("MaThuCung");

                    b.HasIndex("NguoiThucHien");

                    b.ToTable("LichSuTrangThai");
                });

            modelBuilder.Entity("WebApplication1.Models.Newsletter", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Email");

                    b.ToTable("Newsletter");
                });

            modelBuilder.Entity("WebApplication1.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauMaHoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("NamSinh")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("WebApplication1.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MoTaHoatDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGhiNhan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("NhatKyHeThong");
                });

            modelBuilder.Entity("WebApplication1.Models.PhanCongCuuHo", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaBaoCao")
                        .HasColumnType("int");

                    b.Property<int>("MaTinhNguyenVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaTinhNguyenVien");

                    b.HasIndex("MaBaoCao", "MaTinhNguyenVien")
                        .IsUnique();

                    b.ToTable("PhanCongCuuHo");
                });

            modelBuilder.Entity("WebApplication1.Models.QuyenGop", b =>
                {
                    b.Property<int>("MaQuyenGop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyenGop"));

                    b.Property<string>("LoiNhan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayQuyenGop")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNguoiQuyenGop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenQuyQuyenGop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaQuyenGop");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("QuyenGop");
                });

            modelBuilder.Entity("WebApplication1.Models.ThongKeDashboard", b =>
                {
                    b.Property<int>("MaThongKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongKe"));

                    b.Property<int>("NamThongKe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThongKe")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoCongViecHoanThanh")
                        .HasColumnType("int");

                    b.Property<int>("ThangThongKe")
                        .HasColumnType("int");

                    b.Property<int>("TongBaoCaoCuuHo")
                        .HasColumnType("int");

                    b.Property<decimal>("TongChiPhiYTe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TongDonNhanNuoi")
                        .HasColumnType("int");

                    b.Property<int>("TongLuotKhamBenh")
                        .HasColumnType("int");

                    b.Property<int>("TongThuCung")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTienQuyenGop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TongTinhNguyenVien")
                        .HasColumnType("int");

                    b.Property<decimal>("TyLeDuyetDon")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TyLeThamGiaTrungBinh")
                        .HasColumnType("int");

                    b.Property<decimal>("TyLeTuChoiDon")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("MaThongKe");

                    b.HasIndex("NgayThongKe")
                        .IsUnique();

                    b.ToTable("ThongKeDashboard");
                });

            modelBuilder.Entity("WebApplication1.Models.ThuCung", b =>
                {
                    b.Property<int>("MaThuCung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuCung"));

                    b.Property<string>("AnhChinh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DonViTuoi")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("GiaTriTuoi")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GiongThuCung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiNguonGoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCuuHo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenThuCung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhTrangSucKhoe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiCuuHo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiNhanNuoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThuCung");

                    b.ToTable("ThuCung");
                });

            modelBuilder.Entity("WebApplication1.Models.ThuCungYeuThich", b =>
                {
                    b.Property<int>("MaYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuThich"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaThuCung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLuu")
                        .HasColumnType("datetime2");

                    b.HasKey("MaYeuThich");

                    b.HasIndex("MaThuCung");

                    b.HasIndex("MaNguoiDung", "MaThuCung")
                        .IsUnique();

                    b.ToTable("ThuCungYeuThich");
                });

            modelBuilder.Entity("WebApplication1.Models.TinhNguyenVien", b =>
                {
                    b.Property<int>("MaTinhNguyenVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinhNguyenVien"));

                    b.Property<string>("KyNangHienTai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TyLeChuyenCan")
                        .HasColumnType("int");

                    b.HasKey("MaTinhNguyenVien");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("TinhNguyenVien");
                });

            modelBuilder.Entity("WebApplication1.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("WebApplication1.Models.AnhThuCung", b =>
                {
                    b.HasOne("WebApplication1.Models.ThuCung", "ThuCung")
                        .WithMany("AnhThuCungs")
                        .HasForeignKey("MaThuCung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThuCung");
                });

            modelBuilder.Entity("WebApplication1.Models.BaiViet", b =>
                {
                    b.HasOne("WebApplication1.Models.NguoiDung", "TacGia")
                        .WithMany("BaiViets")
                        .HasForeignKey("MaTacGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.ThuCung", "ThuCung")
                        .WithMany("BaiViets")
                        .HasForeignKey("MaThuCung")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TacGia");

                    b.Navigation("ThuCung");
                });

            modelBuilder.Entity("WebApplication1.Models.ChiPhiCuuHo", b =>
                {
                    b.HasOne("WebApplication1.Models.ThuCung", "ThuCung")
                        .WithMany("ChiPhiCuuHos")
                        .HasForeignKey("MaThuCung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.NguoiDung", "NguoiDungXacNhan")
                        .WithMany("ChiPhiCuHos")
                        .HasForeignKey("NguoiXacNhan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDungXacNhan");

                    b.Navigation("ThuCung");
                });

            modelBuilder.Entity("WebApplication1.Models.DiemDanhCongViec", b =>
                {
                    b.HasOne("WebApplication1.Models.CongViecTaiTram", "CongViecTaiTram")
                        .WithMany("DiemDanhCongViecs")
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TinhNguyenVien", "TinhNguyenVien")
                        .WithMany("DiemDanhCongViecs")
                        .HasForeignKey("MaTinhNguyenVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongViecTaiTram");

                    b.Navigation("TinhNguyenVien");
                });

            modelBuilder.Entity("WebApplication1.Models.DonNhanNuoi", b =>
                {
                    b.HasOne("WebApplication1.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonNhanNuois")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.ThuCung", "ThuCung")
                        .WithMany("DonNhanNuois")
                        .HasForeignKey("MaThuCung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("ThuCung");
                });

            modelBuilder.Entity("WebApplication1.Models.KhaoSatDieuKienSong", b =>
                {
                    b.HasOne("WebApplication1.Models.DonNhanNuoi", "DonNhanNuoi")
                        .WithOne("KhaoSatDieuKienSong")
                        .HasForeignKey("WebApplication1.Models.KhaoSatDieuKienSong", "MaDonNhanNuoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonNhanNuoi");
                });

            modelBuilder.Entity("WebApplication1.Models.LichSuSucKhoe", b =>
                {
                    b.HasOne("WebApplication1.Models.ThuCung", "ThuCung")
                        .WithMany("LichSuSucKhoes")
                        .HasForeignKey("MaThuCung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThuCung");
                });

            modelBuilder.Entity("WebApplication1.Models.LichSuTrangThai", b =>
                {
                    b.HasOne("WebApplication1.Models.ThuCung", "ThuCung")
                        .WithMany("LichSuTrangThais")
                        .HasForeignKey("MaThuCung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.NguoiDung", "NguoiDungThucHien")
                        .WithMany("LichSuTrangThais")
                        .HasForeignKey("NguoiThucHien")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDungThucHien");

                    b.Navigation("ThuCung");
                });

            modelBuilder.Entity("WebApplication1.Models.NguoiDung", b =>
                {
                    b.HasOne("WebApplication1.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("WebApplication1.Models.NhatKyHeThong", b =>
                {
                    b.HasOne("WebApplication1.Models.NguoiDung", "NguoiDung")
                        .WithMany("NhatKyHeThongs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebApplication1.Models.PhanCongCuuHo", b =>
                {
                    b.HasOne("WebApplication1.Models.BaoCaoCuuHo", "BaoCaoCuuHo")
                        .WithMany("PhanCongCuuHos")
                        .HasForeignKey("MaBaoCao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TinhNguyenVien", "TinhNguyenVien")
                        .WithMany("PhanCongCuuHos")
                        .HasForeignKey("MaTinhNguyenVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaoCaoCuuHo");

                    b.Navigation("TinhNguyenVien");
                });

            modelBuilder.Entity("WebApplication1.Models.QuyenGop", b =>
                {
                    b.HasOne("WebApplication1.Models.NguoiDung", "NguoiDung")
                        .WithMany("QuyenGops")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebApplication1.Models.ThuCungYeuThich", b =>
                {
                    b.HasOne("WebApplication1.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThuCungYeuThichs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.ThuCung", "ThuCung")
                        .WithMany("ThuCungYeuThichs")
                        .HasForeignKey("MaThuCung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("ThuCung");
                });

            modelBuilder.Entity("WebApplication1.Models.TinhNguyenVien", b =>
                {
                    b.HasOne("WebApplication1.Models.NguoiDung", "NguoiDung")
                        .WithOne("TinhNguyenVien")
                        .HasForeignKey("WebApplication1.Models.TinhNguyenVien", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebApplication1.Models.BaoCaoCuuHo", b =>
                {
                    b.Navigation("PhanCongCuuHos");
                });

            modelBuilder.Entity("WebApplication1.Models.CongViecTaiTram", b =>
                {
                    b.Navigation("DiemDanhCongViecs");
                });

            modelBuilder.Entity("WebApplication1.Models.DonNhanNuoi", b =>
                {
                    b.Navigation("KhaoSatDieuKienSong");
                });

            modelBuilder.Entity("WebApplication1.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiViets");

                    b.Navigation("ChiPhiCuHos");

                    b.Navigation("DonNhanNuois");

                    b.Navigation("LichSuTrangThais");

                    b.Navigation("NhatKyHeThongs");

                    b.Navigation("QuyenGops");

                    b.Navigation("ThuCungYeuThichs");

                    b.Navigation("TinhNguyenVien");
                });

            modelBuilder.Entity("WebApplication1.Models.ThuCung", b =>
                {
                    b.Navigation("AnhThuCungs");

                    b.Navigation("BaiViets");

                    b.Navigation("ChiPhiCuuHos");

                    b.Navigation("DonNhanNuois");

                    b.Navigation("LichSuSucKhoes");

                    b.Navigation("LichSuTrangThais");

                    b.Navigation("ThuCungYeuThichs");
                });

            modelBuilder.Entity("WebApplication1.Models.TinhNguyenVien", b =>
                {
                    b.Navigation("DiemDanhCongViecs");

                    b.Navigation("PhanCongCuuHos");
                });

            modelBuilder.Entity("WebApplication1.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
